process.on('uncaughtException',e=>{console.error(e.message,e.internalQuery||'');process.exit(1)});
import {PGlite} from '@electric-sql/pglite';import {readFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create schema auth;create role anon;create role authenticated;create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb default '{}');create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.actor',true),'')::uuid$$;create table public.organisations(id uuid primary key,name text);create table public.organisation_members(org_id uuid not null,user_id uuid not null,status text not null check(status in ('active','pending','invited')),unique(org_id,user_id));`);
const a='00000000-0000-0000-0000-000000000001',b='00000000-0000-0000-0000-000000000002',c='00000000-0000-0000-0000-000000000003',org='10000000-0000-0000-0000-000000000001';
await db.query(`insert into auth.users(id,email) values($1,'a@example.test'),($2,'b@example.test'),($3,'c@example.test')`,[a,b,c]);await db.query(`insert into organisations values($1,'Test org')`,[org]);await db.query(`insert into organisation_members values($1,$2,'active'),($1,$3,'active'),($1,$4,'active')`,[org,a,b,c]);
await db.exec(await readFile(new URL('./001_rooms.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('./002_delivery.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('./003_attachments.sql',import.meta.url),'utf8'));
const actor=async id=>{await db.query(`select set_config('test.actor',$1,false)`,[id]);await db.exec('set role authenticated');};
const call=async (operation,payload={})=>(await db.query(`select public.boss_rooms_v1($1,$2::jsonb) result`,[operation,JSON.stringify({org_id:org,...payload})])).rows[0].result;
const denied=async fn=>{let failed=false;try{await fn()}catch{failed=true}assert(failed,'Expected request to fail');};
await actor(a);
await denied(()=>db.query('select * from boss_room_reads'));
await denied(()=>db.query('select * from boss_room_attachments'));
await denied(()=>db.query("select boss_rooms_core_v1('organizations','{}')"));
await denied(()=>db.query("select boss_rooms_delivery_v1('organizations','{}')"));
assert.equal((await call('organizations')).length,1);assert.equal((await call('directory')).length,3);
const room=await call('create',{kind:'room',name:'Launch',members:[b],visibility:'private'});const rid=room.id;
await denied(()=>db.query('select * from boss_rooms'));await denied(()=>db.query('insert into boss_room_memory values($1,$2,$3,1)',[org,a,'forged']));
await actor(c);await denied(()=>call('messages',{room_id:rid}));assert.equal((await call('list')).length,0);
await actor(a);const request='20000000-0000-0000-0000-000000000001';let msg=await call('post',{room_id:rid,body:'Hello',request_id:request});assert.equal((await call('post',{room_id:rid,body:'Hello',request_id:request})).id,msg.id);await denied(()=>call('post',{room_id:rid,body:'Different',request_id:request}));
await actor(b);assert.equal((await call('messages',{room_id:rid})).length,1);await denied(()=>call('edit',{room_id:rid,message_id:msg.id,revision:1,body:'Changed by someone else'}));
const other=await call('create',{kind:'room',name:'Other',members:[]});await denied(()=>call('post',{room_id:other.id,parent_id:msg.id,body:'Wrong room',request_id:crypto.randomUUID()}));
await actor(a);msg=await call('edit',{room_id:rid,message_id:msg.id,revision:1,body:'Hello edited'});assert.equal(msg.revision,2);await denied(()=>call('edit',{room_id:rid,message_id:msg.id,revision:1,body:'Stale'}));
const reply=await call('post',{room_id:rid,parent_id:msg.id,body:'Reply',request_id:crypto.randomUUID()});await denied(()=>call('post',{room_id:rid,parent_id:reply.id,body:'Nested',request_id:crypto.randomUUID()}));
msg=await call('pin',{room_id:rid,message_id:msg.id,revision:2,pinned:true});assert.equal((await call('pins',{room_id:rid})).length,1);await call('delete',{room_id:rid,message_id:msg.id,revision:msg.revision});assert.equal((await call('pins',{room_id:rid})).length,0);assert.equal((await call('messages',{room_id:rid,parent_id:msg.id})).length,1);
const personal=await call('create',{kind:'assistant',name:'My assistant',members:[b]});assert.deepEqual(personal.members,[a]);await actor(b);await denied(()=>call('messages',{room_id:personal.id}));await actor(a);assert.equal((await call('create',{kind:'assistant',name:'Mine'})).id,personal.id);
await call('save_memory',{body:'I prefer concise answers.',revision:0});assert.equal((await call('memory')).body,'I prefer concise answers.');await denied(()=>call('save_memory',{body:'stale',revision:0}));await actor(b);assert.equal((await call('memory')).body,'');
const direct=await call('create',{kind:'direct',name:'A and B',members:[a]});await actor(a);assert.equal((await call('create',{kind:'direct',name:'B and A',members:[b]})).id,direct.id);assert.equal((await call('list')).find(r=>r.id===direct.id).name,'b@example.test');await actor(b);assert.equal((await call('list')).find(r=>r.id===direct.id).name,'a@example.test');await actor(a);
const dmMessage=await call('post',{room_id:direct.id,body:'Private direct update',request_id:crypto.randomUUID()});
await actor(b);assert.equal((await call('messages',{room_id:direct.id}))[0].id,dmMessage.id);
await actor(c);await denied(()=>call('messages',{room_id:direct.id}));await denied(()=>call('search',{room_id:direct.id,query:'Private'}));await denied(()=>call('message',{room_id:direct.id,message_id:dmMessage.id}));assert(!(await call('list')).some(r=>r.id===direct.id));await actor(a);
await call('update',{room_id:rid,name:'Launch',members:[a],owner_id:a});await actor(b);await denied(()=>call('messages',{room_id:rid}));
await db.exec('reset role');await db.query("delete from organisation_members where user_id=$1",[a]);await actor(a);await denied(()=>call('memory'));await denied(()=>call('messages',{room_id:personal.id}));await db.exec('reset role');await db.query("insert into organisation_members values($1,$2,'active')",[org,a]);await actor(a);
// BOSS membership uses active/pending/invited; removal deletes the row.
for (const status of ['pending','invited']) {
 await db.exec('reset role');await db.query('update organisation_members set status=$1 where org_id=$2 and user_id=$3',[status,org,c]);await actor(c);
 assert.equal((await call('organizations')).length,0);await denied(()=>call('list'));await denied(()=>call('memory'));
}
await db.exec('reset role');await db.query("update organisation_members set status='active' where org_id=$1 and user_id=$2",[org,c]);await actor(a);
const pub=await call('create',{kind:'room',name:'Open',visibility:'organization'});await actor(c);await denied(()=>call('messages',{room_id:pub.id}));await call('join',{room_id:pub.id});assert.deepEqual(await call('messages',{room_id:pub.id}),[]);await call('leave',{room_id:pub.id});await denied(()=>call('messages',{room_id:pub.id}));await actor('');await denied(()=>call('organizations'));
await actor(a);
const pagesRoom=await call('create',{kind:'room',name:'Paging',members:[]});
for(let i=0;i<5;i++) await call('post',{room_id:pagesRoom.id,body:'page '+i,request_id:crypto.randomUUID()});
const page1=await call('messages',{room_id:pagesRoom.id,limit:2});assert.equal(page1.length,2);assert(page1[0].seq<page1[1].seq);
const page2=await call('messages',{room_id:pagesRoom.id,limit:2,before:page1[0].seq});assert.equal(page2.length,2);assert(page2[1].seq<page1[0].seq);
await denied(()=>call('message',{room_id:pagesRoom.id,message_id:reply.id}));
await denied(()=>call('update',{room_id:personal.id,name:'Share private',members:[a,b],owner_id:a}));
const memory=await call('memory');await call('save_memory',{body:'',revision:memory.revision});assert.equal((await call('memory')).body,'');
await db.exec('reset role; set role anon');await denied(()=>call('organizations'));
console.log('PASS: authenticated RPC, table denial, membership, revocation, idempotency, cross-room threads, edit conflicts, pin/delete, direct deduplication, private assistant/memory isolation, join/leave.');await db.close();
